"""initial_schema

Revision ID: 8f5993c1e378
Revises: 
Create Date: 2025-11-06 01:19:54.035130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f5993c1e378'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('one_default_address'), table_name='addresses', postgresql_where='is_default')
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('cart_items_unique'), 'cart_items', type_='unique')
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_meal_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'])
    op.alter_column('carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('carts_user_id_key'), 'carts', type_='unique')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'])
    op.alter_column('meals', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('meals', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('meals', 'allergens',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('meals', 'calories',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('meals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_meals_name'), table_name='meals')
    op.drop_constraint(op.f('meals_restaurant_id_fkey'), 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'restaurants', ['restaurant_id'], ['id'])
    op.alter_column('moods', 'label',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('moods', 'vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('moods', 'source',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'spotify'::text"))
    op.alter_column('moods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('moods_user_id_fkey'), 'moods', type_='foreignkey')
    op.create_foreign_key(None, 'moods', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('order_items_meal_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'meals', ['meal_id'], ['id'])
    op.alter_column('order_status_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('order_status_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_order_status_events_order_id_created'), table_name='order_status_events')
    op.drop_index(op.f('ix_order_events_order'), table_name='order_status_events')
    op.drop_constraint(op.f('order_status_events_order_id_fkey'), 'order_status_events', type_='foreignkey')
    op.create_foreign_key(None, 'order_status_events', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'preparing', 'dispatched', 'delivered', 'cancelled', 'ready', 'out_for_delivery', 'rejected', 'completed', name='order_status'),
               nullable=True,
               existing_server_default=sa.text("'pending'::order_status"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_orders_restaurant'), table_name='orders')
    op.drop_index(op.f('ix_orders_user'), table_name='orders')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_restaurant_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(op.f('restaurant_staff_user_id_fkey'), 'restaurant_staff', type_='foreignkey')
    op.drop_constraint(op.f('restaurant_staff_restaurant_id_fkey'), 'restaurant_staff', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_staff', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_staff', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('restaurants', sa.Column('latitudes', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('longitudes', sa.Float(), nullable=True))
    op.alter_column('restaurants', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_restaurants_name'), table_name='restaurants')
    op.drop_constraint(op.f('restaurants_owner_id_fkey'), 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'])
    op.drop_column('restaurants', 'latitude')
    op.drop_column('restaurants', 'longitude')
    op.alter_column('sustainability_metrics', 'food_saved_kg',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sustainability_metrics', 'co2_saved_kg',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('sustainability_metrics', 'money_saved',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('sustainability_metrics_order_id_fkey'), 'sustainability_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'sustainability_metrics', 'orders', ['order_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'owner', 'admin', name='user_role'),
               nullable=True,
               existing_server_default=sa.text("'customer'::user_role"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_preferences', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_preferences_user_id_fkey'), 'users_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'users_preferences', 'users', ['user_id'], ['id'])
    op.alter_column('users_spotify_auth_tokens', 'id',
               existing_type=sa.BIGINT(),
               server_default=None,
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users_spotify_auth_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_spotify_auth_tokens', 'expires_at',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_spotify_auth_tokens_user_id_fkey'), 'users_spotify_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'users_spotify_auth_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_spotify_auth_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('users_spotify_auth_tokens_user_id_fkey'), 'users_spotify_auth_tokens', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('users_spotify_auth_tokens', 'expires_at',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('users_spotify_auth_tokens', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_spotify_auth_tokens', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'users_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('users_preferences_user_id_fkey'), 'users_preferences', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('users_preferences', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users_preferences', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'owner', 'admin', name='user_role'),
               nullable=False,
               existing_server_default=sa.text("'customer'::user_role"))
    op.drop_constraint(None, 'sustainability_metrics', type_='foreignkey')
    op.create_foreign_key(op.f('sustainability_metrics_order_id_fkey'), 'sustainability_metrics', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sustainability_metrics', 'money_saved',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sustainability_metrics', 'co2_saved_kg',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sustainability_metrics', 'food_saved_kg',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('restaurants', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key(op.f('restaurants_owner_id_fkey'), 'restaurants', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.alter_column('restaurants', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('restaurants', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('restaurants', 'longitudes')
    op.drop_column('restaurants', 'latitudes')
    op.drop_constraint(None, 'restaurant_staff', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_staff', type_='foreignkey')
    op.create_foreign_key(op.f('restaurant_staff_restaurant_id_fkey'), 'restaurant_staff', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('restaurant_staff_user_id_fkey'), 'restaurant_staff', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_restaurant_id_fkey'), 'orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_orders_user'), 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_orders_restaurant'), 'orders', ['restaurant_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'preparing', 'dispatched', 'delivered', 'cancelled', 'ready', 'out_for_delivery', 'rejected', 'completed', name='order_status'),
               nullable=False,
               existing_server_default=sa.text("'pending'::order_status"))
    op.drop_constraint(None, 'order_status_events', type_='foreignkey')
    op.create_foreign_key(op.f('order_status_events_order_id_fkey'), 'order_status_events', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_order_events_order'), 'order_status_events', ['order_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_order_status_events_order_id_created'), 'order_status_events', ['order_id', 'created_at'], unique=False)
    op.alter_column('order_status_events', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_status_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('order_items_meal_id_fkey'), 'order_items', 'meals', ['meal_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'moods', type_='foreignkey')
    op.create_foreign_key(op.f('moods_user_id_fkey'), 'moods', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('moods', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('moods', 'source',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'spotify'::text"))
    op.alter_column('moods', 'vector',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('moods', 'label',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(op.f('meals_restaurant_id_fkey'), 'meals', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_meals_name'), 'meals', ['name'], unique=False)
    op.alter_column('meals', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('meals', 'calories',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('meals', 'allergens',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('meals', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('meals', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('carts_user_id_key'), 'carts', ['user_id'])
    op.alter_column('carts', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_meal_id_fkey'), 'cart_items', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('cart_items_unique'), 'cart_items', ['cart_id', 'meal_id'])
    op.alter_column('cart_items', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('one_default_address'), 'addresses', ['user_id'], unique=True, postgresql_where='is_default')
    op.alter_column('addresses', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
